In [1]:
import pandas as pd
import pymysql

# Establish connection
db = pymysql.connect(
    host="localhost",
    user="root",
    password="394850",  # Replace with your MySQL password
    database="CompanyDB"
)

# Create a cursor object
cursor = db.cursor()

# Test query
cursor.execute("SHOW TABLES;")

# Fetch and print results
for table in cursor.fetchall():
    print(table)

# Close connection
cursor.close()
db.close()

('customers',)
('departments',)
('employees',)
('orderdetails',)
('orders',)
('products',)

# Using the Orders table, write a SQL query to show:
### OrderID
### OrderDate
### TotalAmount
### The previous order's TotalAmount
## Use LAG() and order the rows by OrderDate.
#### Your task: Write the SQL query.

In [3]:
import pandas as pd
from sqlalchemy import create_engine

# Create a clean database connection engine
engine = create_engine("mysql+pymysql://root:394850@localhost:3306/CompanyDB")

# Describe the table structure
df_desc = pd.read_sql("DESCRIBE orders;", con=engine)

df_desc

         Field           Type Null  Key Default Extra
0      OrderID            int   NO  PRI    None
1   CustomerID            int  YES  MUL    None
2    OrderDate           date  YES         None
3  TotalAmount  decimal(10,2)  YES         None

In [8]:
df_1 = pd.read_sql("""SELECT OrderID,OrderDate,TotalAmount,LAG(TotalAmount) OVER( ORDER BY OrderDate) AS previous_Day_Sales From orders""",con=engine)

In [9]:
df_1.head()

   OrderID   OrderDate  TotalAmount  previous_Day_Sales
0     1001  2024-08-01      65000.0                 NaN
1     1002  2024-08-03      25000.0             65000.0
2     1003  2024-08-05       2300.0             25000.0
3     1004  2024-08-08      18000.0              2300.0
4     1005  2024-08-10      27500.0             18000.0

## 🟢 Question 2 — `LEAD()`

Using the **`Orders`** table, write a SQL query to show:

- `OrderID`
- `OrderDate`
- `TotalAmount`
- The **next order's `TotalAmount`**

Use `LEAD()` and order the rows by `OrderDate`.

**Your task:** Write the SQL query.

In [11]:
df_2 =pd.read_sql("""SELECT OrderID,OrderDate,TotalAmount,LEAD(TotalAmount) OVER (ORDER BY OrderDate) AS next_day_sales FROM ORDERS """,con = engine)

In [13]:
df_2.tail()

   OrderID   OrderDate  TotalAmount  next_day_sales
3     1004  2024-08-08      18000.0         27500.0
4     1005  2024-08-10      27500.0         12000.0
5     1006  2024-08-12      12000.0          3300.0
6     1007  2024-08-15       3300.0         65800.0
7     1008  2024-08-18      65800.0             NaN

## 🟢 Question 3 — `ROW_NUMBER()`

Using the **`Employees`** table, write a SQL query to show:

- `EmployeeName`
- `Salary`
- A **row number** based on salary from highest to lowest

Use `ROW_NUMBER()` with `OVER()`.

**Your task:** Write the SQL query.

In [14]:
df_3 =pd.read_sql("""DESC EMPLOYEES;""",con=engine)
df_3

          Field           Type Null  Key Default Extra
0    EmployeeID            int   NO  PRI    None
1  EmployeeName   varchar(100)   NO         None
2         Email   varchar(150)  YES  UNI    None
3        Salary  decimal(10,2)  YES         None
4      HireDate           date  YES         None
5  DepartmentID            int  YES  MUL    None

In [15]:
df_4 = pd.read_sql("""SELECT EmployeeName,Salary, ROW_NUMBER() OVER(ORDER BY Salary Desc) AS SALARY_RANK FROM EMPLOYEES;""",con=engine)

In [16]:
df_4.head()

  EmployeeName   Salary  SALARY_RANK
0       Suresh  70000.0            1
1        Priya  62000.0            2
2       Vikram  58000.0            3
3       Arshad  55000.0            4
4         Neha  52000.0            5

## 🟢 Question 4 — `RANK()`

Using the **`Employees`** table, write a SQL query to show:

- `EmployeeName`
- `Salary`
- The **rank of each employee based on salary**, from highest to lowest

Use `RANK()` with `OVER()`.

**Your task:** Write the SQL query.

In [18]:
df_5 = pd.read_sql("SELECT EmployeeName,SALARY,RANK() OVER(ORDER BY SALARY DESC) AS SALES_RANK FROM Employees ",con = engine)

In [19]:
df_5.head()

  EmployeeName   SALARY  SALES_RANK
0       Suresh  70000.0           1
1        Priya  62000.0           2
2       Vikram  58000.0           3
3       Arshad  55000.0           4
4         Neha  52000.0           5

## 🟢 Question 5 — `DENSE_RANK()`

Using the **`Employees`** table, write a SQL query to show:

- `EmployeeName`
- `Salary`
- The **dense rank of each employee based on salary**, from highest to lowest

Use `DENSE_RANK()` with `OVER()`.

**Your task:** Write the SQL query.

In [20]:
df_6 = pd.read_sql("SELECT EmployeeName,Salary,DENSE_RANK() OVER(ORDER BY SALARY DESC) FROM Employees",con=engine)

In [21]:
df_6.head()

  EmployeeName   Salary  DENSE_RANK() OVER(ORDER BY SALARY DESC)
0       Suresh  70000.0                                        1
1        Priya  62000.0                                        2
2       Vikram  58000.0                                        3
3       Arshad  55000.0                                        4
4         Neha  52000.0                                        5

## 🟢 Question 6 — `SUM() OVER()`

Using the **`Orders`** table, write a SQL query to show:

- `OrderID`
- `OrderDate`
- `TotalAmount`
- The **running total of `TotalAmount`** based on `OrderDate`

Use `SUM()` with `OVER()` and `ORDER BY`.

**Your task:** Write the SQL query.

In [22]:
df_7 = pd.read_sql("Desc Orders;",con =engine)

In [23]:
df_7.head()

         Field           Type Null  Key Default Extra
0      OrderID            int   NO  PRI    None
1   CustomerID            int  YES  MUL    None
2    OrderDate           date  YES         None
3  TotalAmount  decimal(10,2)  YES         None

In [24]:
df_7 = pd.read_sql("SELECT OrderID,OrderDate,ToTalAmount,SUM(TotalAmount) OVER(ORDER BY ORDERDATE) FROM Orders;",con =engine)

In [25]:
df_7.head()

   OrderID   OrderDate  ToTalAmount  SUM(TotalAmount) OVER(ORDER BY ORDERDATE)
0     1001  2024-08-01      65000.0                                    65000.0
1     1002  2024-08-03      25000.0                                    90000.0
2     1003  2024-08-05       2300.0                                    92300.0
3     1004  2024-08-08      18000.0                                   110300.0
4     1005  2024-08-10      27500.0                                   137800.0

## 🟢 Question 7 — `PARTITION BY`

Using the **`Employees`** table, write a SQL query to show:

- `EmployeeName`
- `DepartmentID`
- `Salary`
- A **row number within each department**, ordered by salary from highest to lowest

Use `ROW_NUMBER()`, `PARTITION BY`, and `ORDER BY`.

**Your task:** Write the SQL query.

In [27]:
df_8 = pd.read_sql("SELECT EmployeeName,DepartmentID,SALARY,ROW_NUMBER() OVER(PARTITION BY DepartmentID ORDER BY Salary Desc) As dept_Salary_rank FROM Employees;",con =engine)
df_8.head()

  EmployeeName  DepartmentID   SALARY  dept_Salary_rank
0       Suresh             1  70000.0                 1
1       Arshad             1  55000.0                 2
2        Rahul             2  48000.0                 1
3        Priya             3  62000.0                 1
4       Anjali             4  45000.0                 1